<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/internal_exam_analysis.php';
require_once __DIR__ . '/../includes/icons.php';
boot_session(); require_role('student','advisor','admin');
$u=current_user(); $id=(int)($_GET['id']??0); $r=internal_analysis($id);
if(!$r || !internal_can_view($r,$u)){ http_response_code(404); die('گزارش یافت نشد'); }
$an=$r['analysis']??[]; $subjects=$r['subjects']??[]; $issues=$r['issues']??[]; $beh=$r['behavior']??[]; $pdfLogo=local_image_data_uri('assets/img/logo.png'); $tpl=local_image_data_uri('assets/img/plan-pdf-template.png');
?><!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><title>تحلیل آزمون داخلی · <?= e($r['student_name']) ?></title><style>
@font-face{font-family:Vazir;src:url('../assets/fonts/Vazirmatn.woff2') format('woff2');font-weight:100 900}*{box-sizing:border-box}body{margin:0;background:#111;color:#172a21;font-family:Vazir,Tahoma,sans-serif;line-height:1.65}.actions{position:sticky;top:0;z-index:9;background:#101c17;padding:12px;text-align:center}.btn{border:0;border-radius:999px;padding:10px 18px;background:#cbac80;color:#121;text-decoration:none;font-weight:900;cursor:pointer}.page{width:210mm;min-height:297mm;margin:12px auto;background:#fbfaf4;position:relative;overflow:hidden;box-shadow:0 20px 60px #0008;page-break-after:always}.page:last-child{page-break-after:auto}.tpl{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:.28}.inner{position:relative;z-index:2;padding:13mm}.top{display:flex;justify-content:space-between;align-items:center;background:linear-gradient(135deg,#172a21,#385b49);color:#fff;border-radius:18px;padding:14px 18px;border:1px solid #cbac80}.brand{display:flex;gap:10px;align-items:center}.logo{width:44px;height:44px;border-radius:14px;background:#fff;overflow:hidden}.logo img{width:100%;height:100%;object-fit:cover}.hero{display:grid;grid-template-columns:1.3fr .7fr;gap:12px;margin:14px 0}.card{background:rgba(255,255,255,.86);border:1px solid #d8dfd8;border-radius:18px;padding:16px}.score{background:linear-gradient(135deg,#142a20,#6b8872);color:#fff;text-align:center}.score b{display:block;font-size:38px;color:#f2d28e}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.stat{text-align:center}.stat b{display:block;font-size:22px;color:#6b8872}.section-title{margin:16px 0 10px;padding:9px 12px;background:linear-gradient(135deg,#172a21,#6b8872);color:#fff;border-radius:14px;font-weight:1000}table{width:100%;border-collapse:collapse;background:#fff;border-radius:14px;overflow:hidden}th{background:#172a21;color:#fff}th,td{padding:9px;border-bottom:1px solid #e4e8e4;font-size:12px;text-align:right}.alerts,.recs{display:grid;gap:8px}.alert,.rec{background:#fff;border:1px solid #e4e8e4;border-radius:14px;padding:10px}.alert b{color:#b55}.footer{margin-top:16px;border:2px dashed #cbac80;border-radius:16px;padding:14px;background:#fffdf6}@media print{.actions{display:none}@page{size:A4;margin:0}body{background:#fff}.page{margin:0;width:210mm;height:297mm;min-height:297mm;box-shadow:none;page-break-after:always}.page:last-child{page-break-after:auto}.inner{padding:11mm}.card{padding:12px}.section-title{margin:10px 0 7px}th,td{padding:7px;font-size:10.5px}}
</style><script>function pr(){setTimeout(()=>print(),150)}</script></head><body><div class="actions"><button class="btn" onclick="pr()">چاپ / ذخیره PDF</button> <a class="btn" href="<?= url($u['role']==='student'?'student/internal_exam_analysis.php?attempt='.(int)$r['attempt_id']:'admin/internal_exam_reports.php?student='.(int)$r['student_id']) ?>">بازگشت</a></div>
<section class="page"><img class="tpl" src="<?= $tpl ?>"><div class="inner"><header class="top"><div class="brand"><div class="logo"><img src="<?= $pdfLogo ?>"></div><div><b>مَدار</b><br><small>تحلیل آزمون داخلی مَدار</small></div></div><div><?= jalali_date('now',true) ?></div></header><div class="hero"><div class="card"><h1>پرونده تحلیل آزمون داخلی</h1><p>دانش‌آموز: <b><?= e($r['student_name']) ?></b> · <?= e($r['student_field']??'') ?> <?= $r['student_grade']?'· '.e($r['student_grade']):'' ?></p><p>آزمون: <b><?= e($r['exam_title']) ?></b> · ثبت آزمون: <?= jalali_date($r['submitted_at'],true) ?></p></div><div class="card score"><span>شاخص تحلیل مَدار</span><b><?= fa_num($an['overall']??0) ?>٪</b><span><?= e($an['overall_label']??'') ?></span></div></div><div class="grid4"><div class="card stat"><span>نمره کل</span><b><?= fa_num(round((float)$r['total_score'],1)) ?>٪</b></div><div class="card stat"><span>درست</span><b><?= fa_num($r['correct_count']??'-') ?></b></div><div class="card stat"><span>غلط</span><b><?= fa_num($r['wrong_count']??'-') ?></b></div><div class="card stat"><span>نزده</span><b><?= fa_num($r['blank_count']??'-') ?></b></div></div><div class="section-title">جمع‌بندی هوشمند</div><div class="card"><p><?= e($an['summary']??'') ?></p></div><div class="section-title">هشدارها و پیشنهادها</div><div class="alerts"><?php foreach(($an['alerts']??[]) as $al): ?><div class="alert"><b><?= e($al['title']) ?></b><br><?= e($al['text']) ?></div><?php endforeach; ?></div><div class="recs" style="margin-top:8px"><?php foreach(($an['recommendations']??[]) as $rec): ?><div class="rec">💡 <?= e($rec) ?></div><?php endforeach; ?></div></div></section>
<section class="page"><img class="tpl" src="<?= $tpl ?>"><div class="inner"><header class="top"><div class="brand"><div class="logo"><img src="<?= $pdfLogo ?>"></div><div><b>ریزتحلیل آزمون داخلی</b><br><small><?= e($r['student_name']) ?></small></div></div><div>صفحه ۲</div></header><div class="section-title">ریز عملکرد درس‌ها</div><?php if($subjects): ?><table><thead><tr><th>درس</th><th>درست</th><th>غلط</th><th>نزده</th><th>درصد</th></tr></thead><tbody><?php foreach($subjects as $s): ?><tr><td><?= e($s['name']) ?></td><td><?= fa_num($s['correct']??'-') ?></td><td><?= fa_num($s['wrong']??'-') ?></td><td><?= fa_num($s['blank']??'-') ?></td><td><?= fa_num($s['percent']??'-') ?>٪</td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="card">ریزدرس‌ها ثبت نشده است.</div><?php endif; ?><div class="section-title">رفتار آزمونی</div><div class="grid4"><div class="card stat"><span>خواب</span><b><?= fa_num($beh['sleep_hours']??'-') ?> ساعت</b></div><div class="card stat"><span>استرس</span><b><?= fa_num($beh['stress_score']??'-') ?></b></div><div class="card stat"><span>تمرکز</span><b><?= fa_num($beh['focus_score']??'-') ?></b></div><div class="card stat"><span>مدیریت زمان</span><b style="font-size:18px"><?= e($beh['time_management']??'—') ?></b></div></div><div class="section-title">ریشه‌یابی سوالات غلط/نزده</div><?php if(!empty($issues)): ?><table><thead><tr><th>سوال</th><th>درس</th><th>وضعیت</th><th>علت</th><th>توضیح</th></tr></thead><tbody><?php 
$reason_labels = [
    'concept' => 'ضعف مفهومی',
    'careless_calc' => 'بی‌دقتی محاسباتی',
    'careless_read' => 'بی‌دقتی خواندن سوال',
    'forgot' => 'فراموشی نکته',
    'doubt' => 'شک بین دو گزینه',
    'trap' => 'تله آموزشی',
    'time_rush' => 'شتاب‌زدگی زمان',
    'bubble_err' => 'خطای پاسخبرگ',
    'not_studied' => 'عدم مطالعه مبحث',
    'not_mastered' => 'عدم تسلط کافی',
    'no_time' => 'کمبود زمان',
    'too_hard' => 'سختی سوال',
    'doubt_many' => 'شک چند گزینه',
    'strategy' => 'استراتژی غلط',
    'careless' => 'بی‌دقتی',
    'time' => 'کمبود زمان',
    'unknown' => 'نامشخص'
];
foreach(array_slice($issues,0,28) as $is): 
  $r_lbl = $reason_labels[$is['reason'] ?? 'unknown'] ?? 'نامشخص';
?><tr><td><?= fa_num($is['question_number']??'-') ?></td><td><?= e($is['subject']??'') ?></td><td><?= $is['type']==='blank'?'نزده':'غلط' ?></td><td><?= e($r_lbl) ?></td><td><?= e($is['note']??'') ?></td></tr><?php endforeach; ?></tbody></table><?php else: ?><div class="card">ریشه‌یابی سوالات ثبت نشده است.</div><?php endif; ?><div class="section-title">نقشه اقدام</div><div class="recs"><?php foreach(($an['action_plan']??[]) as $rec): ?><div class="rec">✅ <?= e($rec) ?></div><?php endforeach; ?></div><div class="footer"><b>یادداشت دانش‌آموز:</b><br><?= nl2br(e($r['student_note']??'—')) ?></div></div></section></body></html>