<?php
require_once __DIR__ . '/../includes/auth.php';
require_once __DIR__ . '/../includes/internal_exam_analysis.php';
require_once __DIR__ . '/../includes/helpers.php';
boot_session(); require_role('student','advisor','admin');
$u=current_user(); $id=(int)($_GET['id']??0); $r=internal_analysis($id);
if(!$r || !internal_can_view($r,$u)){ http_response_code(404); die('گزارش یافت نشد'); }
$an=$r['analysis']??[]; $subjects=$r['subjects']??[]; $issues=$r['issues']??[];
?>
<!doctype html><html lang="fa" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>تحلیل آزمون داخلی مَدار</title><style>
@font-face{font-family:MadarPDF;src:url('../assets/fonts/DejaVuSans.ttf')}@font-face{font-family:MadarPDF;src:url('../assets/fonts/DejaVuSans-Bold.ttf');font-weight:800}*{box-sizing:border-box}body{margin:0;background:#101c17;font-family:MadarPDF,Tahoma,sans-serif;color:#172a21}.actions{position:sticky;top:0;z-index:5;background:#0c1512;padding:12px;text-align:center}.btn{display:inline-block;border:0;border-radius:999px;padding:10px 18px;background:#b2945f;color:#111;text-decoration:none;font-weight:800;margin:0 4px}.btn.ghost{background:#25352e;color:#fff}.page{width:210mm;min-height:297mm;margin:14px auto;background:#fcfdf9;border-radius:18px;overflow:hidden;box-shadow:0 20px 70px #0008;padding:18mm}.top{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:2px solid #dfe7df;padding-bottom:8mm;margin-bottom:8mm}.brand{display:flex;gap:10px;align-items:center}.logo{width:54px;height:54px;border-radius:16px;background:#fff;border:2px solid #b2945f;overflow:hidden}.logo img{width:100%;height:100%;object-fit:cover}.brand b{font-size:24px}.muted{color:#627169}.hero{display:grid;grid-template-columns:1fr 170px;gap:12px;margin-bottom:8mm}.card{background:#fff;border:1px solid #dfe7df;border-radius:18px;padding:16px;box-shadow:0 6px 22px #14211b10}.score{text-align:center;background:linear-gradient(135deg,#f5ead2,#fff)}.score b{display:block;font-size:38px;color:#b2945f}.grid4{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:8mm}.stat{text-align:center}.stat span{display:block;color:#627169;font-size:11px;font-weight:800}.stat b{font-size:24px}.section-title{font-weight:900;font-size:18px;margin:8mm 0 3mm;color:#172a21;border-right:5px solid #6b8872;padding-right:8px}.alerts{display:grid;grid-template-columns:1fr 1fr;gap:8px}.alert{border-right:4px solid #d9b25f}.rec{margin:5px 0;padding:9px 12px;border-radius:12px;background:#f7faf7;border:1px solid #dfe7df}.subjects{width:100%;border-collapse:collapse;background:#fff;border-radius:14px;overflow:hidden}th,td{border:1px solid #dfe7df;padding:8px;text-align:center;font-size:12px}th{background:#edf3ee}.issues{display:flex;flex-wrap:wrap;gap:6px}.issues span{background:#f6f1e8;border:1px solid #e6d6b8;border-radius:999px;padding:5px 9px;font-size:11px}@media print{body{background:#fff}.actions{display:none}.page{margin:0;border-radius:0;box-shadow:none;width:210mm;min-height:297mm;page-break-after:always}}
</style><script>function pr(){setTimeout(()=>print(),150)}</script></head><body onload="pr()"><div class="actions"><a class="btn ghost" href="<?= url('student/internal_exam_analysis.php?attempt='.(int)$r['attempt_id']) ?>">بازگشت</a><button class="btn" onclick="print()">چاپ / ذخیره PDF</button></div><section class="page"><header class="top"><div class="brand"><div class="logo"><img src="<?= asset('img/logo.png') ?>"></div><div><b>مَدار</b><br><small class="muted">تحلیل آزمون داخلی مَدار</small></div></div><div class="muted"><?= jalali_date('now',true) ?></div></header><div class="hero"><div class="card"><h1>پرونده تحلیل آزمون داخلی</h1><p class="muted">دانش‌آموز: <b><?= e($r['student_name']) ?></b> · آزمون: <b><?= e($r['exam_title']) ?></b> · ثبت آزمون: <?= jalali_date($r['submitted_at'],true) ?></p></div><div class="card score"><span>شاخص تحلیل</span><b><?= fa_num($an['overall']??0) ?>٪</b><span><?= e($an['overall_label']??'') ?></span></div></div><div class="grid4"><div class="card stat"><span>نمره کل</span><b><?= fa_num(round((float)$r['total_score'],1)) ?>٪</b></div><div class="card stat"><span>درست</span><b><?= fa_num($r['correct_count']) ?></b></div><div class="card stat"><span>غلط</span><b><?= fa_num($r['wrong_count']) ?></b></div><div class="card stat"><span>نزده</span><b><?= fa_num($r['blank_count']) ?></b></div></div><div class="section-title">جمع‌بندی هوشمند</div><div class="card"><p><?= e($an['summary']??'') ?></p></div><div class="section-title">هشدارها و پیشنهادها</div><div class="alerts"><?php foreach(($an['alerts']??[]) as $al): ?><div class="card alert"><b><?= e($al['title']) ?></b><br><?= e($al['text']) ?></div><?php endforeach; ?></div><div class="card" style="margin-top:8px"><?php foreach(($an['recommendations']??[]) as $rec): ?><div class="rec">💡 <?= e($rec) ?></div><?php endforeach; ?></div><div class="section-title">ریزنتیجه درس‌ها</div><table class="subjects"><tr><th>درس</th><th>درست</th><th>غلط</th><th>نزده</th><th>درصد</th></tr><?php foreach($subjects as $s): ?><tr><td><?= e($s['name']) ?></td><td><?= fa_num($s['correct']) ?></td><td><?= fa_num($s['wrong']) ?></td><td><?= fa_num($s['blank']) ?></td><td><?= fa_num($s['percent']) ?>٪</td></tr><?php endforeach; ?></table><div class="section-title">سوالات غلط/نزده تشخیص‌داده‌شده توسط سیستم</div><div class="issues"><?php foreach(array_slice($issues,0,80) as $it): ?><span><?= fa_num($it['question_number']) ?> · <?= e($it['subject']) ?> · <?= $it['type']==='blank'?'نزده':'غلط' ?></span><?php endforeach; ?></div></section></body></html>
